### ISSUE TITLE
make it trusted by AV

### ISSUE THREAD

**Issue by rubaboo** [Todd1561/TANWindowMgr#15]
Without admin rights it's not possible to override the antivirus and run the program.

**Comment by Todd1561** [comment]
I just use built-in Windows Defender and have never had a problem, so I'm not sure what your particular software is complaining about.  From my research there's at least a couple issues; 1) my app isn't signed with a Code Signing Certificate and 2) many AV apps use a 'trusted' list that gets built after many people use the app and report it as safe.

The code signing certs are not cheap and given this app generates -$5,000/year (e.g. generates nothing, only costs money) that's just never going to happen, sorry.  Even if I got a certificate I'd probably never pass the second test since this is such a low-use app.  My suggestion would be to add the app to whatever whitelist your AV program has to just bypass any checking.  Again, I don't know anything about your particular AV but I imagine they all have this kind of functionality.

Thanks for checking out the software!

Todd
