### ISSUE TITLE
Can't savestate opened folders in exlorer

### ISSUE THREAD

**Issue by Timurama** [Todd1561/TANWindowMgr#17]
is this such a complicated thing that it's not possible for this prog?

**Comment by Todd1561** [comment]
I'm not entirely sure what you're asking, but I think you're talking about saving the location of Windows File Explorer windows?  If so that's the same issue outlined in https://github.com/Todd1561/TANWindowMgr/issues/2 it's a problem because TANWindowMgr tracks windows based on the underlying executable name that owns them.  This works fine in most situation but not when the process spawns multiple windows, as is the case here.

You might try https://www.desksoft.com/WindowManager.htm  it's not free but it's commercial software that has presumably far more resources behind it than I can dedicate to this freeware.  It has the ability to identify windows by name and also executable, the former may work for you.
